In [11]:
import datetime
import pytz #timezones module
import pandas as pd
import numpy as np

my_tz = 'Europe/London' #INPUT TIMEZONE, IN PYTZ FORMAT - CHOOSE FROM DROPDOWN
their_tz = 'Australia/Sydney' #INPUT TIMEZONE, IN PYTZ FORMAT - CHOOSE FROM DROPDOWN
my_early_time_limit = datetime.time(10, 0, 0) #INPUT EARLIEST AVAILABLE TIME
my_late_time_limit = datetime.time(22, 0, 0) #INPUT LATEST AVAILABLE TIME
their_early_time_limit = datetime.time(18, 0, 0) #INPUT EARLIEST AVAILABLE TIME
their_late_time_limit = datetime.time(22, 0, 0) #INPUT LATEST AVAILABLE TIME

if my_tz in pytz.all_timezones:
    my_dt = datetime.datetime.now(pytz.timezone(my_tz))
    print('My time:', my_dt)
    my_offset = my_dt.utcoffset()
else: print('Incorrect timezone, check entry you willy')

if their_tz in pytz.all_timezones:
    their_dt = datetime.datetime.now(pytz.timezone(their_tz))
    print('Their time:', their_dt)
    their_offset = their_dt.utcoffset()
else: print('Incorrect timezone, check entry you willy')

if my_offset > their_offset: #need to account for same time zone
    time_difference = my_offset - their_offset
    preposition = 'behind'
else: time_difference = their_offset - my_offset
preposition = 'ahead'

print('They are', time_difference, preposition) #assess time offset behind/ahead issue

My time: 2022-04-16 23:13:14.040243+01:00
Their time: 2022-04-17 08:13:14.041238+10:00
They are 9:00:00 ahead

In [12]:
my_time_midnight = (datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0))
my_time = [my_time_midnight.time()]
their_time_midnight = my_time_midnight + time_difference
their_time = [their_time_midnight.time()]
timestep = datetime.timedelta(hours=1)

for i in range (1, 24):
    my_time.append((my_time_midnight + i * timestep).time())

for i in range (1, 24):
    their_time.append((their_time_midnight + i * timestep).time())

combined_times = {'My time': my_time,
                  'Their time': their_time
                 }

df = pd.DataFrame(combined_times)
df

     My time Their time
0   00:00:00   09:00:00
1   01:00:00   10:00:00
2   02:00:00   11:00:00
3   03:00:00   12:00:00
4   04:00:00   13:00:00
5   05:00:00   14:00:00
6   06:00:00   15:00:00
7   07:00:00   16:00:00
8   08:00:00   17:00:00
9   09:00:00   18:00:00
10  10:00:00   19:00:00
11  11:00:00   20:00:00
12  12:00:00   21:00:00
13  13:00:00   22:00:00
14  14:00:00   23:00:00
15  15:00:00   00:00:00
16  16:00:00   01:00:00
17  17:00:00   02:00:00
18  18:00:00   03:00:00
19  19:00:00   04:00:00
20  20:00:00   05:00:00
21  21:00:00   06:00:00
22  22:00:00   07:00:00
23  23:00:00   08:00:00

In [13]:
my_early_index_limit = df.loc[df['My time'] == my_early_time_limit].index
my_late_index_limit = df.loc[df['My time'] == my_late_time_limit].index

df_truncate = df.iloc[my_early_index_limit[0]:my_late_index_limit[0]+1].reset_index(drop=True)
df_truncate

     My time Their time
0   10:00:00   19:00:00
1   11:00:00   20:00:00
2   12:00:00   21:00:00
3   13:00:00   22:00:00
4   14:00:00   23:00:00
5   15:00:00   00:00:00
6   16:00:00   01:00:00
7   17:00:00   02:00:00
8   18:00:00   03:00:00
9   19:00:00   04:00:00
10  20:00:00   05:00:00
11  21:00:00   06:00:00
12  22:00:00   07:00:00

In [14]:
their_early_index_limit = df_truncate.loc[df_truncate['Their time'] == their_early_time_limit].index
their_late_index_limit = df_truncate.loc[df_truncate['Their time'] == their_late_time_limit].index

df_availability = df_truncate.iloc[their_early_index_limit[0]:their_late_index_limit[0]+1].reset_index(drop=True)
df_availability

IndexError: index 0 is out of bounds for axis 0 with size 0

In [15]:
#need to add functionality that allows for availability cut off
#i.e. after df is truncated to say 8pm their time
#but their availability is from 4pm

#ideal would be to receive a mask from the front end (in some format)
#and combine this with the df